<a href="https://colab.research.google.com/github/rafaza24/Pemrograman-Lanjut-Python-DS23/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pengantar Matrix

In [ ]:
A = [[0 for j in range(20)] for i in range(10)]

print(A)

In [9]:
n = int(input("Masukan baris : "))
m = int(input("Masukan kolom : "))

A = [[0 for j in range(m)] for i in range(n) ]

for i in range(n):
  for j in range(m):
    A[i][j] = int(input(f"masukan elemen baris ke-{str(i+1)} kolom ke-{str(j+1)} :"))

for i in range(n):
  for j in range(m):
    print(A[i][j],end=" ")
  print("")

Masukan baris : 3
Masukan kolom : 3
masukan elemen baris ke-1 kolom ke-1 :1
masukan elemen baris ke-1 kolom ke-2 :2
masukan elemen baris ke-1 kolom ke-3 :3
masukan elemen baris ke-2 kolom ke-1 :4
masukan elemen baris ke-2 kolom ke-2 :5
masukan elemen baris ke-2 kolom ke-3 :6
masukan elemen baris ke-3 kolom ke-1 :7
masukan elemen baris ke-3 kolom ke-2 :8
masukan elemen baris ke-3 kolom ke-3 :9
1 2 3 
4 5 6 
7 8 9 


Menggunakan Library

In [10]:
import numpy as np

x1 = np.array([[2,3,4],[2,5,6],[6,7,8]])
x1

array([[2, 3, 4],
       [2, 5, 6],
       [6, 7, 8]])

menggunakan list

In [11]:
ls = [[2,3,4],[2,5,6],[6,7,8]]
ls

[[2, 3, 4], [2, 5, 6], [6, 7, 8]]

In [12]:
A = [[0 for j in range(20)] for i in range(10)]
A

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

dot = perkalian

In [17]:
x2 = np.dot(x1,x1)
x2

array([[ 34,  49,  58],
       [ 50,  73,  86],
       [ 74, 109, 130]])

LATIHAN

NOMOR 1

In [19]:
n = int(input("Masukkan jumlah baris Matrix segitiga Pascal: "))

pascal = []

for i in range(n):
    baris = [1] * (i + 1)
    for j in range(1, i):
        baris[j] = pascal[i-1][j-1] + pascal[i-1][j]
    pascal.append(baris)
    print(" ".join(map(str, baris)))


Masukkan jumlah baris Matrix segitiga Pascal: 5
1
1 1
1 2 1
1 3 3 1
1 4 6 4 1


NOMOR 2

A

In [17]:
#2a
import numpy as np
A = np.array([[1,2],[3,4]])
print(A)
determinan_A = np.linalg.det(A)
print(f"Determinan dari matrix a adalah {int(determinan_A)}\n")

B = np.array([[-1,3,0],[2,1,-5],[1,4,-2]])
print(B)
determinan_B = np.linalg.det(B)
print(f"Determinan dari matrix b adalah {int(determinan_B)}\n")

[[1 2]
 [3 4]]
Determinan dari matrix a adalah -2

[[-1  3  0]
 [ 2  1 -5]
 [ 1  4 -2]]
Determinan dari matrix b adalah -21



B

In [11]:
A = [[1,3,7,2],[5,8,-9,0],[6,-7,11,12]]
transpose = [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]

print("\nTranspose matriks A")
for baris in transpose:
    print(baris)


Transpose matriks A
[1, 5, 6]
[3, 8, -7]
[7, -9, 11]
[2, 0, 12]
